adding GadflyNode with frame
atlas-blocks/atlas pull request #108
Opened 2022-08-13 13:20 UTC by roman-timo

2022-08-19 20:08 UTC, AlexFreik commented on frontend/components/document/Navbar.tsx
> +	};
1. this logic is not for the `navbar`
2. when user import graph i think it should appear as a new tab, so we don't need this function anymore

2022-08-19 20:42 UTC, AlexFreik requested changes

2022-08-19 20:42 UTC, AlexFreik commented on frontend/components/document/PropsPanel.tsx
> +		props: new InputState('props', useState<any>(null)),
no no no) it makes types weaker, it is better to add another object:
```ts
gladifyProps: new InputState('props', useState< GadflyPlotProps>(null)),
```

2022-08-19 20:42 UTC, AlexFreik commented on frontend/components/document/frames/UiPlotFrame.tsx
> +		<>
you need to delete this)

2022-08-19 20:42 UTC, AlexFreik commented on frontend/components/document/frames/UiPlotFrame.tsx
> +	setPlotHtml = setPlotHtml.replace('<?xml version="1.0" encoding="UTF-8"?>', '');
1. You can do this instead)
```ts
const firstResultHtml = (firstResult && firstResult['text/html']) ? firstResult['text/html'] : '';
const setPlotHtml = firstResultHtml
        .replace('width="141.42mm"', 'width="100%"')
        .replace('height="100mm"', 'height="100%"');
        .replace('<html>', '');
        .replace('</html>', '');
....
```
2. it looks you are doing some bulshit and there is easier way

2022-08-19 20:42 UTC, AlexFreik commented on frontend/src/graph/nodes/AtlasNode.ts
> +		.filter((node) => node.name.startsWith(prefix))
1. you also need to check that what after prefix is number.
2. so it is better to use separate function for this check because it will be easier to read

```ts

function isDefaultName(name: string, prefix = 'b') {
	return name.startsWith(prefix) && !isNaN(Number(name.slice(1)));
}
```

2022-08-19 20:42 UTC, AlexFreik commented on frontend/src/graph/nodes/GadflyNode.ts
> +	}
this functions will be inherited from parent

2022-08-19 20:42 UTC, AlexFreik commented on frontend/src/kernels/JuliaExecuter.ts
> +
it looks is better without this newlines, because this comments are just separators

2022-08-19 20:42 UTC, AlexFreik commented on frontend/src/graph/nodes/GadflyNode.ts
> +		this.type = GadflyNode.ui_type;
delete this line, and it will be treated like an expression node by executer

2022-08-19 20:42 UTC, AlexFreik commented on frontend/src/kernels/JuliaExecuter.ts
> +		[GadflyNode.ui_type]: getExpressionCode,
you can delete this

2022-08-20 15:30 UTC, roman-timo commented on frontend/components/document/Navbar.tsx
> +	};
don't know where to put this.. just left it for now

2022-08-20 15:30 UTC, roman-timo commented on frontend/components/document/PropsPanel.tsx
> +		props: new InputState('props', useState<any>(null)),
fixed

2022-08-20 15:30 UTC, roman-timo commented on frontend/components/document/frames/UiPlotFrame.tsx
> +		<>
fixed

2022-08-20 15:31 UTC, roman-timo commented on frontend/components/document/frames/UiPlotFrame.tsx
> +	setPlotHtml = setPlotHtml.replace('<?xml version="1.0" encoding="UTF-8"?>', '');
Made it pretty so you like it :)

2022-08-20 15:31 UTC, roman-timo commented on frontend/src/graph/nodes/AtlasNode.ts
> +		.filter((node) => node.name.startsWith(prefix))
fixed with better solution

2022-08-20 15:32 UTC, roman-timo commented on frontend/src/graph/nodes/GadflyNode.ts
> +	}
deleted.

2022-08-20 15:32 UTC, roman-timo commented on frontend/src/kernels/JuliaExecuter.ts
> +
fixed

2022-08-20 15:32 UTC, roman-timo commented on frontend/src/graph/nodes/GadflyNode.ts
> +		this.type = GadflyNode.ui_type;
done

2022-08-20 15:32 UTC, roman-timo commented on frontend/src/kernels/JuliaExecuter.ts
> +		[GadflyNode.ui_type]: getExpressionCode,
done

2022-08-20 16:14 UTC, AlexFreik commented on frontend/src/kernels/JuliaExecuter.ts
> -
i think you accedentaly deleted it

2022-08-20 16:28 UTC, AlexFreik commented on frontend/components/document/PropsPanel.tsx
> +		),
it looks ugly)

If you make it a `class` instead of `type` you can just do `new GadflyPlotProps()`: 
```ts
class GadflyPlotProps {
    colorKey = '';
    xLabel = '';
    ...
}
```

2022-08-20 16:37 UTC, AlexFreik commented on frontend/components/document/props/GadflyProps.tsx
> +	if (!inputState.state) return <div key={'gf_empty'}></div>;
what is this?

2022-08-20 17:01 UTC, AlexFreik requested changes

2022-08-20 21:10 UTC, roman-timo commented on frontend/components/document/LibPanel.tsx
> +		GadflyNode: () => GadflyNode.build().setHtmlResult('').setDefaultName(wiu.graph, 'gadfly'),
fixed. added default graphics

2022-08-20 21:13 UTC, roman-timo commented on frontend/components/document/props/GadflyProps.tsx
> +import styles from '../../../styles/GadflyNode.module.css';
color.. is a bit strange name for each layer of graphics (in Gadfly). Somehow they mean color = 'name in the Legend'. But at the same time you can set a color in this parameter using color=[colorant"orange"].. :))) don't know why is so..

2022-08-20 21:14 UTC, roman-timo commented on frontend/src/kernels/JuliaExecuter.ts
> -
got it back

2022-08-20 21:14 UTC, roman-timo commented on frontend/components/document/PropsPanel.tsx
> +		),
done.

2022-08-20 21:15 UTC, roman-timo commented on frontend/components/document/props/GadflyProps.tsx
> +	if (!inputState.state) return <div key={'gf_empty'}></div>;
need a key here. Fixed - changed to React.Fragment

2022-08-20 21:15 UTC, roman-timo commented on frontend/components/document/frames/UiAtlasGraphFrame.tsx
> +				const reactFlowBounds = reactFlowWrapper.current!.getBoundingClientRect();
don't know why this error still shows up

2022-08-23 11:59 UTC, AlexFreik approved these changes

2022-08-23 12:34 UTC, AlexFreik approved these changes

2022-08-23 12:34 UTC, merged