New group node
atlas-blocks/atlas pull request #115
Opened 2022-08-25 20:48 UTC by roman-timo

2022-09-02 18:43 UTC, AlexFreik requested changes

2022-09-02 18:43 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +		}
```ts
		if (druggedNode !== null) {
			const resetedNode = {
				...druggedNode,
				ui_parentNode: undefined,
			}
			setDruggedNode(resetedNode);
			setSelectedNode(null);
		}
```

2022-09-02 18:43 UTC, AlexFreik commented on frontend/src/graph/nodes/AtlasNode.ts
> +	public ui_height?: number;
can be moved into group node

2022-09-02 18:43 UTC, AlexFreik commented on frontend/src/graph/nodes/AtlasNode.ts
> +	public ui_parentNode?: string;
it is better to make it `string | null`. We tend to use `null`s in our code

Also it is better to not duplicate dat in two places, because managing its consistency is pain in a**)) 

Lets get rid of `parentId` field for all nodes and leave only `membersId`.
Instead we can put a functional getter
```ts
getParentId(graph: AtlasGraph): string | null {
    let parentId =  null;
    // some logic
    return parentId;
}
```

2022-09-02 18:43 UTC, AlexFreik commented on frontend/src/graph/nodes/AtlasNode.ts
> +	public ui_height?: number;
and it is better to have default values like `0`, instead of edge case when it is `undefined`, because all group nodes will have them

2022-09-02 18:43 UTC, AlexFreik commented on frontend/src/kernels/JuliaExecuter.ts
> +			await this.setNodeProviderNames(node as ScriptNode);
It seems you don't undertand my language, ahah)

`this.setNodeProviderNames(node)` is usually a "setter", it sets property of `this`. So it is confusing when it is actually sets property of its argument `node`.

2022-09-02 18:43 UTC, AlexFreik commented on frontend/src/kernels/JuliaExecuter.ts
> +	public async setNodeProviderNames(node: ScriptNode): Promise<void> {
Also there is no reason to make this function public

2022-09-02 18:43 UTC, AlexFreik commented on frontend/src/kernels/JuliaExecuter.ts
> +		providerNodes.forEach((prov_node) => {
`prov_node`))) we are sticking with the `camelCase` for the variable names (`ui_` is exception)

2022-09-02 18:43 UTC, AlexFreik commented on frontend/src/graph/nodes/AtlasNode.ts
> +	public ui_expandParent?: boolean;
can be deleted

2022-09-03 14:22 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
> +		}
done

2022-09-03 14:22 UTC, roman-timo commented on frontend/src/graph/nodes/AtlasNode.ts
> +	public ui_height?: number;
done

2022-09-03 14:23 UTC, roman-timo commented on frontend/src/graph/nodes/AtlasNode.ts
> +	public ui_parentNode?: string;
Don't understand this...) Is there any strong reason to do this??)

2022-09-03 14:23 UTC, roman-timo commented on frontend/src/kernels/JuliaExecuter.ts
> +			await this.setNodeProviderNames(node as ScriptNode);
fixed

2022-09-03 14:24 UTC, roman-timo commented on frontend/src/kernels/JuliaExecuter.ts
> +	public async setNodeProviderNames(node: ScriptNode): Promise<void> {
fixed

2022-09-03 14:24 UTC, roman-timo commented on frontend/src/kernels/JuliaExecuter.ts
> +		providerNodes.forEach((prov_node) => {
fixed

2022-09-03 14:24 UTC, roman-timo commented on frontend/src/graph/nodes/AtlasNode.ts
> +	public ui_expandParent?: boolean;
this is needed for any node.. why to delete this..?

2022-09-03 14:30 UTC, roman-timo commented
Also could you check pls why the GroupNode always gets bak to the original size after loading a graph. Actually I was trying a lot to fix this. Even it's not a GroupNode only, but any node gets back to the original size after reload.
You can do simple:
- add GroupNode and resize it
- create new graph
- get back to recent graph with GroupNode

2022-09-05 17:06 UTC, AlexFreik approved these changes

2022-09-06 18:00 UTC, merged