update docs
atlas-blocks/atlas pull request #120
Opened 2022-09-04 20:32 UTC by AlexFreik

2022-09-05 09:09 UTC, roman-timo requested changes

2022-09-05 09:09 UTC, roman-timo commented on docs/docs/we-are-hiring.md
> +- the hurt of the project - a businessman with a programming background.
I think this docs is fantastic, except maybe only this one thing. I don't fully get what did you mean by "the hurt of the project" O_o Ahahhahha))) This phrase gonna make me hurt  hahahaha))) Maybe I should fix this businessman so he is not a hurt for our project anymore. Will talk to him! )))hahah)))

2022-09-05 17:10 UTC, AlexFreik commented on docs/docs/we-are-hiring.md
> +- the hurt of the project - a businessman with a programming background.
ahah) true

2022-09-05 17:11 UTC, AlexFreik commented on docs/docs/we-are-hiring.md
> +- the hurt of the project - a businessman with a programming background.
fixed, thaks)

2022-09-09 09:32 UTC, roman-timo approved these changes
all good

2022-09-09 11:17 UTC, merged