Visual imporvements
atlas-blocks/atlas pull request #124
Opened 2022-09-19 09:06 UTC by roman-timo

Restyled and improved new Atlas Interface

2022-09-21 05:39 UTC, AlexFreik requested changes

2022-09-21 05:39 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +const getRelativeExecutionCount = (node: ScriptNode, graph: AtlasGraph) => {
should be `function`

2022-09-21 05:39 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +const getTitle = (node: AtlasNode) => {
should be function

2022-09-21 05:39 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +					<div className={styles.blockCounter}>
maybe you can increase counter size a bit

2022-09-21 05:39 UTC, AlexFreik commented on frontend/components/ObjectsPanel.tsx
> +	const libElements = {
you can add real blocks here. for example plot block with normal distribution

2022-09-21 05:39 UTC, AlexFreik commented on frontend/components/UiAtlasWindow.tsx
> +		event.stopPropagation();
what it does?

2022-09-21 05:39 UTC, AlexFreik commented on frontend/components/UiAtlasWindow.tsx
> +		awu.setSelectedFrame(0);
you forgot to remove this line. you already setting `selectedFrame` in line 55

2022-09-23 08:05 UTC, roman-timo commented on frontend/components/UiAtlasWindow.tsx
> +		awu.setSelectedFrame(0);
This is needed to select 0-frame everytime any Frame is closed. Otherwise it tries to show the Frame that was closed and throws error.

2022-09-23 08:05 UTC, roman-timo commented on frontend/components/ElementsPanel.tsx
> +			selectedNode !== node ? styles.element : styles.element + ' ' + styles.elementSelected;
fixed.

2022-09-23 17:49 UTC, AlexFreik commented on frontend/components/UiAtlasWindow.tsx
> +		event.stopPropagation();
you can add a comment

2022-09-27 10:23 UTC, roman-timo reviewed
?

2022-09-27 10:23 UTC, roman-timo commented on frontend/components/UiAtlasWindow.tsx
> +		awu.setSelectedFrame(0);
fixed

2022-09-27 12:03 UTC, AlexFreik commented on frontend/components/UiAtlasWindow.tsx
> +		if (deleteIndex <= awu.selectedFrameIndex) awu.setSelectedFrameIndex(switchIndex);
why not just 
```ts
awu.setSelectedFrameIndex(switchIndex)
```
wihtout if statement?

2022-09-27 19:59 UTC, roman-timo commented on frontend/components/UiAtlasWindow.tsx
> +		if (deleteIndex <= awu.selectedFrameIndex) awu.setSelectedFrameIndex(switchIndex);
If deleteIndex > selectedFrame then we don't need to switch selectedFrame. 
If I make (switchIndex) it will set current frame to selected-1, that we don't need to do.

2022-09-28 06:32 UTC, AlexFreik approved these changes

2022-09-28 06:34 UTC, merged