added jupyter notebook converter
atlas-blocks/atlas pull request #125
Opened 2022-09-25 19:49 UTC by AlexFreik

2022-09-27 10:35 UTC, roman-timo requested changes

2022-09-27 10:35 UTC, roman-timo commented on frontend/components/frames/UiNotebookViewerFrame.tsx
> +				language="python"
language python?? )

2022-09-27 10:35 UTC, roman-timo commented on frontend/src/frames/NotebookViewerFrame.ts
> +	public getType(): string {
is it a good thing to have multiple methods for same function..? Maybe just rename it for simplicity?

2022-09-27 10:35 UTC, roman-timo commented on frontend/src/utils/notebook_utils.ts
> +			const right = b.execution_count === null ? 0 : b.execution_count;
this could be just 
`Number(a.execution_count)`

2022-09-27 10:39 UTC, roman-timo commented
just why it is black...??)

2022-09-27 12:41 UTC, AlexFreik commented on frontend/components/frames/UiNotebookViewerFrame.tsx
> +				language="python"
the only options are "r" and "python"

2022-09-27 12:42 UTC, AlexFreik commented on frontend/src/frames/NotebookViewerFrame.ts
> +	public getType(): string {
one is static, and other one is not. It is to be able to do

```ts
if (AtlasGraphFrame.getType() == frame.getType()) do something;
```

2022-09-27 12:44 UTC, AlexFreik commented
> just why it is black...??)

The other option is solarizedl and it is shit)

<img width="436" alt="Screenshot 2022-09-27 at 14 43 31" src="https://user-images.githubusercontent.com/61039123/192529489-783333a9-ef98-4f83-a236-d06f606d949c.png">

2022-09-27 13:07 UTC, AlexFreik commented
Updated the theme

<img width="1438" alt="Screenshot 2022-09-27 at 15 06 45" src="https://user-images.githubusercontent.com/61039123/192534627-6c85be88-26ef-4e7a-947e-3bd91b68096a.png">

2022-09-27 13:07 UTC, AlexFreik commented on frontend/src/utils/notebook_utils.ts
> +			const right = b.execution_count === null ? 0 : b.execution_count;
Ahah, indeed) fixed

2022-09-30 14:49 UTC, roman-timo approved these changes
Good to go

2022-10-02 15:53 UTC, roman-timo approved these changes
Good

2022-10-02 15:56 UTC, merged