refactoring + added new node
atlas-blocks/atlas pull request #128
Opened 2022-10-03 05:49 UTC by AlexFreik

2022-10-12 13:34 UTC, AlexFreik commented on frontend/components/LibPanel.tsx
> +			ExpressionNode.ui_type,
it is safer to use ui_types instead of typo-prone strings

2022-10-12 13:34 UTC, AlexFreik commented on frontend/pages/api/login.ts
> -		setCookie(
nothing changed here, just prettier reformated it

2022-10-19 14:39 UTC, roman-timo requested changes

2022-10-19 14:39 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
> +	return ScriptWrapper(node, latexWrapper(node.getLatex() ? node.getLatex() : node.getContent()));
can use nullish coalascing
`node.getLatex() ?? node.getContent()`

2022-10-19 14:39 UTC, roman-timo commented on frontend/src/utils/json_utils.ts
> +	return JSON.stringify(object, undefined, space);
do we really need this oneliner?
maybe more obvious to send directly JSON.stringify when needed?

Also I think jsonStringToGraph - is redundant, as i only check if everything is ok with graphString. Which is also done at jsonToGraph.
Maybe we just leave jsonToGraph and make all necessary stringify and checks there?

2022-10-19 14:39 UTC, roman-timo commented on frontend/components/LibPanel.tsx
> +		Plots: [DesmosNode.ui_type, GadflyNode.ui_type],
Let's leave it as Graphics. Not all will be plots... maybe we will add Dash soon.

2022-10-19 18:06 UTC, AlexFreik commented on frontend/components/LibPanel.tsx
> +		return ui_type.split('AtlasGraph.')[1].split('Node')[0];
Yes, because now we use ui_type

2022-10-19 18:09 UTC, AlexFreik commented on frontend/components/LibPanel.tsx
> +		Plots: [DesmosNode.ui_type, GadflyNode.ui_type],
I can change it if you want, but I think plots should have a separate section since there will be many different plots

2022-10-19 18:17 UTC, AlexFreik commented on frontend/src/utils/json_utils.ts
> +	return JSON.stringify(object, undefined, space);
1. Yes, I think we need this stringify function. Right now it is one liner, but it might not be the case in the future. So if it will be changed, then we will need change all places where it was used, which is not so nice. Also i think it is more consistent to use until funcs for both stringifying and parsing

2022-10-20 06:23 UTC, roman-timo approved these changes

2022-10-20 16:35 UTC, roman-timo approved these changes
Ok

2022-10-20 16:35 UTC, merged