Nodes improvements
atlas-blocks/atlas pull request #130
Opened 2022-10-08 20:48 UTC by roman-timo

- added duplication for nodes
- added Copy Result
- removed result from FunctionNode as it has no need
- improved SourceNode - now it can select matrix rows
- change example node to csv2matrix

2022-10-12 13:39 UTC, AlexFreik requested changes

2022-10-12 13:39 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +	const duplicateNode = () => {
why don't you use `JsonUtils` to convert node to string when user types Ctlr + C and then again `JsonUtils` on Ctrl + V?

2022-10-12 19:16 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
> +	const duplicateNode = () => {
hm... this is very different way, didn't think about it.
Isuppose.. anyway we will have to (1) create a new Instance and (2) reassign all methods thru Object.assign. And then (3) set some default props as id.
Is jsonUtils better?

2022-10-12 20:20 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +	const duplicateNode = () => {
yes, because 
- JsonUtils is literally made for this
- right now every time you add new node you will need to update this place

2022-10-14 07:57 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
> +	const duplicateNode = () => {
Now looks better with JsonUtils :)) thx

2022-10-15 22:08 UTC, AlexFreik requested changes

2022-10-15 22:08 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +			.setUiPosition(node.ui_position[0] + 100, node.ui_position[1] + 100)
magic numbers)

2022-10-15 22:08 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +	const duplicateNode = () => {
isn't it nicer to add `Ctrl + C / V` shortcuts instead of button?

2022-10-15 22:11 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +		//TO-FIX this selection of newNode doesn't work. Pls fix.
TODO ))

2022-10-16 16:21 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
> +	const duplicateNode = () => {
fixed

2022-10-16 16:51 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
> +			.setUiPosition(node.ui_position[0] + 100, node.ui_position[1] + 100)
fixed

2022-10-16 16:53 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
> +	const duplicateNode = () => {
it is temporary solution. It's gonna be a small icon at the top of the block to duplicate at one click. Maybe also will add ctrl-c/v as well.
Since our context menu is not dirty yet... I put everything there))

2022-10-16 16:54 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
> +		//TO-FIX this selection of newNode doesn't work. Pls fix.
fixed (only TODO fixed, not the issue ))haha)

2022-10-18 08:02 UTC, AlexFreik requested changes

2022-10-18 09:26 UTC, roman-timo commented on frontend/components/frames/UiAtlasGraphFrame.tsx
> +			handler = onDoubleClickMap[GadflyNode.ui_type];
Yes, I'm doing some models for prospect clients and add small things as it goes. Anyway it is still "node improvements" branch.
This one thing - is to handle doubleclik on any image/svg result - Plots.plot, Gadfly.plot, etc, on ExpressionNode.

2022-10-18 09:28 UTC, AlexFreik approved these changes

2022-10-19 06:36 UTC, merged