Draft: migration to v10 of reactflow
atlas-blocks/atlas pull request #27
Opened 2022-05-20 17:02 UTC by AlexFreik

2022-05-20 18:13 UTC, roman-timo requested changes

2022-05-20 18:13 UTC, roman-timo commented on frontend/components/document/DnDFlow.tsx
>  import dynamic from 'next/dynamic';
I think you can just "import Background from react-flow.." and delete this one from next.

2022-05-20 18:18 UTC, AlexFreik commented on frontend/components/document/DnDFlow.tsx
>  import dynamic from 'next/dynamic';
true, it doesn't result in an error anymore

2022-05-20 20:02 UTC, AlexFreik commented on frontend/components/document/DnDFlow.tsx
>  import dynamic from 'next/dynamic';
fixed

2022-05-21 08:41 UTC, roman-timo approved these changes
Looks ok!

2022-05-21 08:49 UTC, merged