Blockmenu migration
atlas-blocks/atlas pull request #36
Opened 2022-05-31 22:16 UTC by roman-timo

2022-06-01 09:53 UTC, AlexFreik requested changes
Please run `$ make pretty`

Also, when you make a pr, please quickly check what you have changed. This way you will quickly find yourself some obvious issues like styling, changed `package-lock.json` and etc

2022-06-01 10:48 UTC, AlexFreik commented
Also, it is better if you run pretty before each commit you make. Otherwise you are messing git history of the files

2022-06-02 07:50 UTC, roman-timo commented on frontend/components/document/DnDFlow.tsx
> +	// This should be updated to new v10 style with useNodeState
OK. I delete it then.

2022-06-02 07:50 UTC, roman-timo commented on frontend/components/document/DnDFlow.tsx
> +				y: event.clientY - reactFlowBounds.top - 20,
Since I dont' know how to access width and height of the default block, I use these numbers.

2022-06-02 07:50 UTC, roman-timo commented on frontend/components/document/DnDFlow.tsx
> +			// webInterfaceUtils.refreshUiElements();
Deleted.

2022-06-02 07:50 UTC, roman-timo commented on frontend/components/document/LibPanel.tsx
> +				<span>{name.slice(0, 4)}</span>
We don't have a 'short-name' for blocks I use a name of block type which is long.

2022-06-02 07:50 UTC, roman-timo commented on frontend/components/document/PropsPanel.tsx
> +			// webInterfaceUtils.refreshUiElements()
Yes, this is when you explain me how to change the name)) I tried, but too many errors in wiu.UpdateGraph()

2022-06-02 07:50 UTC, roman-timo commented on frontend/components/document/DnDFlow.tsx
> +	// This should be updated to new v10 style with useNodeState
Fixed

2022-06-02 07:51 UTC, AlexFreik commented on frontend/components/document/LibPanel.tsx
> +				<span>{name.slice(0, 4)}</span>
oke, lets leave it like this

2022-06-02 10:22 UTC, roman-timo commented on frontend/components/document/DnDFlow.tsx
> +					x: event.clientX - reactFlowBounds.left - height / 2,
I suppose should be "width"

2022-06-02 10:22 UTC, roman-timo commented on frontend/components/document/DnDFlow.tsx
> +				// @ts-ignore
Do we need this ignore? I think works fine without this comment

2022-06-02 10:23 UTC, AlexFreik commented on frontend/components/document/DnDFlow.tsx
> +				// @ts-ignore
<img width="736" alt="Screenshot 2022-06-02 at 12 23 51" src="https://user-images.githubusercontent.com/61039123/171609857-d0ad1f2d-9be5-49bd-9db4-37e169bc8949.png">

2022-06-02 10:24 UTC, AlexFreik commented on frontend/components/document/DnDFlow.tsx
> +				// @ts-ignore
<img width="877" alt="Screenshot 2022-06-02 at 12 24 32" src="https://user-images.githubusercontent.com/61039123/171609947-a6b8eeda-be79-4503-b9d0-eec24adda756.png">

2022-06-02 10:26 UTC, AlexFreik commented on frontend/components/document/DnDFlow.tsx
> +					x: event.clientX - reactFlowBounds.left - height / 2,
fixed

2022-06-02 10:28 UTC, AlexFreik reviewed
good now

2022-06-02 10:28 UTC, AlexFreik approved these changes
lgtm

2022-06-02 10:28 UTC, merged