Add matrixfilter block
atlas-blocks/atlas pull request #39
Opened 2022-06-04 14:30 UTC by roman-timo

2022-06-04 15:32 UTC, AlexFreik requested changes
I don't know why, but it was very hard to read your code this time

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +	const refMxName = useRef<any>('');
why any? you can put types

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +		'broadcast(' + opr + ',' + mxName + '[..,' + num + '], ' + val + ')';
we don't have syntax `a[1, 2]`. You should use `getindex(a, 1, 2)`

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +	const getExprCols = (mxName: string, num: string, opr: string, val: string) =>
why the argument is called `num`? it can also be a string. For example, you filter columns that eaqulal to "true"

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +						id={'rows'}
you can't have elements with the same `id` (line 150 and 157)

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +					</button>
Maybe we can add the logical filter the same way as operator? Right now it is hard to see which logical operator you used

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/PropsPanel.tsx
> +		console.log(webInterfaceUtils.setSelectedNode);
console.log

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/PropsPanel.tsx
> +		return <MatrixFilterBuilder setNewContentValue={setNewContentValue} />;
```ts
if (webInterfaceUtils.selectedNode instanceof MatrixFilterNode) {
    return <MatrixFilterBuilder setNewContentValue={setNewContentValue} />;
}
```

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +	const refMxName = useRef<any>('');
It may be better to use full names. Weird short forms like `mx` instead of `matrix` or `fltr` instead of `filter` are harder to read. And you can forget what you have meant in the future. We have powerful IDE's and it is no longer a problem to have a long names, since you can just type few first characters and press tab.

Also, if you want to use short forms it is better to use first letters, like `exp` instead of `expression`

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +			fltrRows.map((obj: any, index: any) =>
what is this?) the name `obj` doesn't tell a thing to me. Also, why are you using `any`?

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +				}),
```ts
obj.exp = getExprRows(
    refMxName.current.value,
    refRow.current[0][index].value,
    refRow.current[1][index].value,
    refRow.current[2][index].value,
),
```

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +	finalExp = refMxName.current.value + '[' + resCols + ', ' + resRows + ']';
we doesn't support this syntax, use `getindex`

2022-06-04 15:32 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +					ref={(el: any) =>
any again

2022-06-04 15:40 UTC, AlexFreik requested changes

2022-06-04 15:40 UTC, AlexFreik commented on frontend/utils/AtlasGraph.ts
> +	// }
what are those comments?

2022-06-04 15:40 UTC, AlexFreik commented on frontend/utils/AtlasGraph.ts
> +	static uitype = 'MatrixFilterNode';
you need both static and non-static fields for json to work properly

```ts
static structUitype = 'MatrixFilterNode';
static uitype;
```

2022-06-04 20:51 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +	const refMxName = useRef<any>('');
fixed

2022-06-04 20:51 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +		'broadcast(' + opr + ',' + mxName + '[..,' + num + '], ' + val + ')';
fixed

2022-06-04 20:52 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +	const getExprCols = (mxName: string, num: string, opr: string, val: string) =>
num - is for the number (or index) of columns and rows on which conditions apply

2022-06-04 20:53 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +						id={'rows'}
fixed

2022-06-04 20:53 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +					</button>
maybe later. for beta version.. ))

2022-06-04 20:58 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +	const refMxName = useRef<any>('');
fixed

2022-06-04 20:59 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +			fltrRows.map((obj: any, index: any) =>
fixed

2022-06-04 21:01 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +				}),
This way doesnt work as this is the State, so I have to use Object.assign()

2022-06-04 21:02 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +	finalExp = refMxName.current.value + '[' + resCols + ', ' + resRows + ']';
fixed

2022-06-04 21:04 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +					ref={(el: any) =>
I have to leave 'any' as it becomes a mess to check on possible null in array of arrays for HTMLElement. Spent 2h on this already. Let me know if you know better way here.

2022-06-04 21:04 UTC, roman-timo commented on frontend/utils/AtlasGraph.ts
> +	// }
fixed

2022-06-04 21:06 UTC, roman-timo commented on frontend/utils/AtlasGraph.ts
> +	static uitype = 'MatrixFilterNode';
Cannot get what you mean here.. let's discuss

2022-06-05 09:41 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +					ref={(el: any) =>
fixed in today's commit!

2022-06-05 12:29 UTC, AlexFreik requested changes

2022-06-05 12:29 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +	const refMxName = useRef<any>('');
i was talking about all the instances where you have used `mx`, `opr`, `fltr`, ...

2022-06-05 12:29 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +			fltrRows.map((obj: any, index: any) =>
if you don't have any type it means type is any)))

2022-06-05 12:29 UTC, AlexFreik commented on frontend/components/document/MatrixFilterBuilder.tsx
> +				}),
then why you don't use `setState`?

2022-06-06 07:46 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +	const getExprCols = (mxName: string, num: string, opr: string, val: string) =>
left it for now as is. I think they are pretty clear here. And they are local, doesn't interfere with anything else.

2022-06-06 07:46 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +						id={'rows'}
fixed now

2022-06-06 07:47 UTC, roman-timo commented on frontend/components/document/PropsPanel.tsx
> +		console.log(webInterfaceUtils.setSelectedNode);
fixed

2022-06-06 07:47 UTC, roman-timo commented on frontend/components/document/PropsPanel.tsx
> +		return <MatrixFilterBuilder setNewContentValue={setNewContentValue} />;
fixed

2022-06-06 07:47 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +			fltrRows.map((obj: any, index: any) =>
fixed

2022-06-06 07:49 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +						refCol.current[1][index].value === '='
fixed

2022-06-06 17:10 UTC, AlexFreik commented on frontend/components/document/PropsPanel.tsx
> +		);
it is better to use if statement here. It is not super readable with ternary operator. Plus if we will add more uitypes we will be using if statement

2022-06-06 17:42 UTC, roman-timo commented on frontend/components/document/PropsPanel.tsx
> +		);
Fixed.

2022-06-07 05:55 UTC, AlexFreik requested changes
I created a new pull request #41 . After we merge it into this branch we can move on with this filter.

2022-06-07 06:35 UTC, AlexFreik approved these changes

2022-06-07 07:51 UTC, merged