added Elements Panel and some styles
atlas-blocks/atlas pull request #40
Opened 2022-06-06 14:59 UTC by roman-timo

How can I merge this branch with recent 'add-matrixfilter' branch??

2022-06-06 17:27 UTC, AlexFreik requested changes

2022-06-06 17:27 UTC, AlexFreik commented on frontend/pages/document.tsx
> +					elsPanelStyleWrapper={styles.elementsPanel}
- it is better to not use short forms, especially for such wide-scope variables  (it may be better to use `elements` instead of `els`) 
- why do you need to pass it? you can just wrap it here
```tsx
< className={styles.elementsPanel}>
    <ElementsPanel webInterfaceUtils={webInterfaceUtils} />
 </>
 ```

2022-06-06 19:14 UTC, roman-timo commented on frontend/pages/document.tsx
> +					elsPanelStyleWrapper={styles.elementsPanel}
Fixed

2022-06-06 22:32 UTC, AlexFreik commented on frontend/components/document/ElementsPanel.tsx
> +			: (selectedStyle = styles.elsElement);
It is hard to read this lines. You shouldn't use ternary operator all over the place) ternary operator meant for small operations like `a = condition ? 5 : 6` since it is more compact than if statement. in this case if statement is much more readable
```ts
let selectedStyle = styles.elsElement 
if (webInterfaceUtils.selectedNode == node) {
    selectedStyle += ' ' + styles.elsElementSelected;
} 
```

2022-06-06 22:35 UTC, AlexFreik commented on frontend/components/document/ElementsPanel.tsx
> +				<span>: {node.type.slice(11, node.type.length)}</span>
it is bad practice to put css inside js . Also what the heck is `node.type.slice(11, node.type.length)` ?) 
I can't tell what are you doing here) It is better to sepparate it into a new function that describes what you are doing (or create a variable at least)

```
function myDescriptiveName(type: string) {
    return type.slice(11, type.length)
} 
```

2022-06-07 05:51 UTC, AlexFreik requested changes

2022-06-07 05:51 UTC, AlexFreik commented on frontend/components/document/ElementsPanel.tsx
> +	function listElements(node: AtlasNode): JSX.Element {
The name `listElements` is not very good) The function doesn't list elements. It creates `JSX` from `AtlasNode`, so it should be named `getNodeUiForElementsPanel` or something like this

2022-06-07 05:51 UTC, AlexFreik commented on frontend/styles/BtnStyle.module.css
> +.justBtn:hover {
what is `justBtn` ? Does it mean that this class can not be used with other classes or what?

2022-06-07 05:51 UTC, AlexFreik commented on frontend/styles/ElementsPanel.module.css
> +.elsElement {
omg) what the heck `elsElement` mean? does it mean `elementsElement`?)

2022-06-07 08:07 UTC, roman-timo commented on frontend/components/document/ElementsPanel.tsx
> +			: (selectedStyle = styles.elsElement);
fixed.

2022-06-07 08:21 UTC, roman-timo commented on frontend/components/document/ElementsPanel.tsx
> +	function listElements(node: AtlasNode): JSX.Element {
fixed

2022-06-07 08:22 UTC, roman-timo commented on frontend/styles/ElementsPanel.module.css
> +.elsElement {
)) I knew u would ask this))
fixed.

2022-06-07 08:55 UTC, AlexFreik commented on frontend/styles/BtnStyle.module.css
> +.justBtn:hover {
then maybe we should name it `generalButton` ?

2022-06-07 08:57 UTC, AlexFreik requested changes

2022-06-07 08:57 UTC, AlexFreik commented on frontend/components/document/ElementsPanel.tsx
> +			selectedStyle += ' ' + `${styles.elementSelected}`;
why are you doing `${styles.elementSelected}` instead of `styles.elementSelected` ?

2022-06-07 08:57 UTC, AlexFreik commented on frontend/components/document/ElementsPanel.tsx
> +	function getElements(node: AtlasNode): JSX.Element {
why `getElements` method get you one element?)

2022-06-07 09:00 UTC, roman-timo commented on frontend/components/document/ElementsPanel.tsx
> +	function getElements(node: AtlasNode): JSX.Element {
I think it's better getElements as we are talking only about UI here, cannot be missleading

2022-06-07 09:03 UTC, roman-timo commented on frontend/components/document/ElementsPanel.tsx
> +			selectedStyle += ' ' + `${styles.elementSelected}`;
Thought it wouldnt work like this. But it's working. will make commit.

2022-06-07 09:05 UTC, AlexFreik commented on frontend/components/document/ElementsPanel.tsx
> +	function getElements(node: AtlasNode): JSX.Element {
if not ui then `getPanelElement`

2022-06-07 09:08 UTC, roman-timo commented on frontend/components/document/ElementsPanel.tsx
> +	function getElements(node: AtlasNode): JSX.Element {
fixed

2022-06-07 09:08 UTC, roman-timo commented on frontend/components/document/ElementsPanel.tsx
> +			selectedStyle += ' ' + `${styles.elementSelected}`;
done

2022-06-07 09:09 UTC, roman-timo commented on frontend/styles/BtnStyle.module.css
> +.justBtn:hover {
let's leave it. It's understood)

2022-06-07 09:16 UTC, AlexFreik approved these changes

2022-06-07 09:18 UTC, merged