Add export import json
atlas-blocks/atlas pull request #46
Opened 2022-06-11 12:39 UTC by roman-timo

2022-06-11 13:18 UTC, AlexFreik requested changes

2022-06-11 13:18 UTC, AlexFreik commented on frontend/styles/Block.module.css
> +}
this class is not used apparently

2022-06-11 13:18 UTC, AlexFreik commented on frontend/components/document/Navbar.tsx
> +		: styles.fileMenu + ' ' + styles.fileMenuHidden;
```ts
const fileMenuStyle = styles.fileMenu + (isFileMenuOpen ? '' : ' ' + styles.fileMenuHidden);
```

2022-06-11 13:18 UTC, AlexFreik commented on frontend/components/document/Navbar.tsx
> +		setIsFileMenuOpen(false);
this code should not be in this function. It is out of place. Move it up

2022-06-11 13:18 UTC, AlexFreik commented on frontend/components/document/Navbar.tsx
> +	const removeRecent = (evt: React.MouseEvent<HTMLDivElement>) => {
what are you removing? what is `recent`?

2022-06-11 13:18 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +	};
`WebInterfaceUtils` is only for the staff connected to the `react-flow`. This should be placed in another utils class. Something like `StorageUtils` or more general class

2022-06-11 13:18 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +		try {
why `try`? what can happen?

2022-06-11 13:18 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +			this.saveGraphToLocalStorage();
You are coupling classes. We don't need this logic inside WIU. Maybe you can just create
```ts
useEffect(() => {
    storageUtils.saveGraphToLocalStorage(wiu.graph);
}, [wiu.graph.nodes]);
```
inside `DnDFlow.ts`?

2022-06-11 13:45 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
> +				<span className={styles.attribute_name}>content: </span> {data.node.content}
something left after my experiments..) fixed

2022-06-11 13:46 UTC, roman-timo commented on frontend/components/document/DnDFlow.tsx
> +import React, { useState, useCallback, useRef, MouseEvent as ReactMouseEvent } from 'react';
That wasn't me. I thought it was your idea, so I didn't change it ))

2022-06-11 13:46 UTC, roman-timo commented on frontend/components/document/MatrixFilterBuilder.tsx
> +		refMatrixName.current?.value ? setNewContentValue(finalExp) : '';
ok. agree. fixed

2022-06-11 13:48 UTC, roman-timo commented on frontend/styles/Navbar.module.css
> +.fileMenu {
I read an article where they advise not to use id for style in react. And also I think className for style have more strong logic. Because id is sometime used for iterate thru array of divs and get click by currentTarget.id or other things. I prefer to keep classNames for all styling unless any hard stops on that)

2022-06-11 13:49 UTC, roman-timo commented on frontend/styles/Navbar.module.css
> +.recentStyle {
ok. removed 'Style' from all classes in css. :)
fixed

2022-06-11 13:49 UTC, roman-timo commented on frontend/components/document/Navbar.tsx
> +		setIsFileMenuOpen(false);
could you please explain what do u mean? setIsFileOpen - should be inside exportToFile.

2022-06-11 13:50 UTC, roman-timo commented on frontend/components/document/Navbar.tsx
> +	const removeRecent = (evt: React.MouseEvent<HTMLDivElement>) => {
recent - is a list of recent user's graphs which are stored in the LocalStorage

2022-06-11 13:51 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +	};
I think wiu - is a nice tool for all functions with graph and UI of graph. Untill we have many-many functions let's keep it al inside wiu. Now it's not too many-many yet )) :)

2022-06-11 13:53 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +		try {
oh.. many things can happen) if json is not really json sintax or it is corrupted etc.

2022-06-11 13:55 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +			this.saveGraphToLocalStorage();
I wont all changes to be immediately saved to LocalStorage. I think it's the best place to fire re-save because it is a single point of any changes to the graph.

2022-06-11 14:05 UTC, AlexFreik commented on frontend/components/document/Navbar.tsx
> +		setIsFileMenuOpen(false);
What is the return type?

2022-06-11 14:05 UTC, AlexFreik commented on frontend/components/document/Navbar.tsx
> +	const removeRecent = (evt: React.MouseEvent<HTMLDivElement>) => {
So maybe you can name it `removeListOfRecentGraphs` ?

2022-06-11 14:05 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +			this.saveGraphToLocalStorage();
> all changes to be immediately saved to LocalStorage

Why? there is no harm if it saved a few milliseconds later. Now you are creating coupling between two logical actions -- updating react-flow and saving graph to the local storage. It is Anti-pattern

2022-06-11 14:05 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +		try {
then create a new function in some utils file that read json file and handles possible errors. And use this function here

2022-06-11 14:05 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +	};
> nice tool for all functions with graph and UI of graph

Will it be nice when WIU becomes 1000+ lines of some mixed logic?

2022-06-11 14:06 UTC, AlexFreik requested changes
some threads are still unresolved

2022-06-11 14:20 UTC, roman-timo commented on frontend/components/document/Navbar.tsx
> +		setIsFileMenuOpen(false);
I'm exporting full graph - wiu.graph into a file. This function doesn't return anything, just save a file.

2022-06-11 14:22 UTC, roman-timo commented on frontend/components/document/Navbar.tsx
> +	const removeRecent = (evt: React.MouseEvent<HTMLDivElement>) => {
it is better would be "removeOneRecentFromRecentList" - but that is too much for the name. removeRecent - is understood, isn't it? what else could be "recent"? :)

2022-06-11 14:24 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +	};
)) I think we can come up to this when we see wiu is overloaded. Maybe after another functionality added (don't know what is coming). As for today, I think we can still keep wiu utils)

2022-06-11 14:25 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +		try {
I suppose that would be too much for now. Unless I understand what could be errors with JSON and how to handle it - then I can write a "helper" function to give a hit to a user what's wrong with his file.

2022-06-11 14:29 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +			this.saveGraphToLocalStorage();
hm... not sure. If we will be updating the graph for any reason, I don't want to remember to save it to LS. So it is performed in 100% cases. Thus better to keep it inside.
It is like "refreshUiElements" inside wiu - it is called any time we need refresh event from WIU itself.

2022-06-11 15:07 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +	};
Rom, if we can do something today we shouldn't leave it for tomorrow. 
My arguments for separating logic into different files:
- it allows to keep files short and therefore easier to navigate
- when different logic is not mixed together it is easier to read

What are your arguments for mixing different things in one big file?

2022-06-11 15:31 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +		try {
tell me what is more readable:
```ts
// WebInterfaceUtils.ts
public loadGraphToUi = (graphData: string | null) => {
    if (!graphData) return;
    try {
        const newGraph = ServerUtils.jsonToGraph(JSON.parse(graphData));
        this.graph.nodes = newGraph.nodes;
        this.graph.edges = newGraph.edges;
        this.graph.name = newGraph.name;
        this.setSelectedNode(null);
        this.refreshUiElements();
    } catch (e) {
        alert(e);
    }
};
```

or

```ts
// WebInterfaceUtils.ts
public replaceCurrentGraphFromString(graphData: string): void {
    const newGraph: AtlasGraph = JsonUtils.jsonStringToGraph(graphData);
    if (newGraph !== null) {
        Object.assign(this.graph, newGraph);
        this.setSelectedNode(null);
     }
}
```

```ts
// JsonUtils.ts
public static jsonStringToGraph(graphData: string): AtlasGraph {
     try {
        return newGraph = JsonUtils.jsonToGraph(JSON.parse(graphData));
    } catch (e) {
        console.error(e)
        alert("Something went wrong while processing new graph");
    }
   return null;
}
```

2022-06-11 15:39 UTC, AlexFreik commented on frontend/components/document/Navbar.tsx
> +	const removeRecent = (evt: React.MouseEvent<HTMLDivElement>) => {
> but that is too much for the name

What do you mean? There are some random code examples from https://github.com/microsoft/vscode-jupyter. It is not a math or physics. Long name is great as long as it has small scope


<img width="693" alt="Screenshot 2022-06-11 at 17 34 09" src="https://user-images.githubusercontent.com/61039123/173194521-846fe434-7255-4d6e-964f-a0cd7c3543e7.png">
<img width="675" alt="Screenshot 2022-06-11 at 17 34 53" src="https://user-images.githubusercontent.com/61039123/173194557-9f262022-5bf7-4076-9649-ec94a9e018b9.png">

Their names are even longer
- `CellOutputDisplayIdTracker`
- `CellExecutionMessageHandlerService`
- `trackKernelResourceInformation`
- `getAssociatedNotebookDocument`


Also, what the heck `removeOneRecentFromRecentList` means? Why would you want to remove one recent?

2022-06-11 15:43 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +			this.saveGraphToLocalStorage();
> I don't want to remember to save it to LS

It is opposite. If you have `useEffect` it will be updating automatically and you don't even need to think about it. Also graph can be changed in some different places, but `useEffect` will handle all of it, isn't it (if you do it right way)?

2022-06-11 15:45 UTC, AlexFreik commented on frontend/utils/ServerUtils.ts
>  	}
why it is inside ServerUtils? You can move it inside `JsonUtils.ts` to prevent coupling of different logic in one file

2022-06-11 15:46 UTC, AlexFreik requested changes
some threads unresolved

2022-06-11 15:46 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +	};
It will also mean new imports..
It really depends on the scale. At this scale it is not necessary to divide into small bits. I can't see what other functions would be added into wiu, can't even imagine) If I can't imagine, means we don't need to do something we even can't see a reason.
Also, once this is needed - we can easily restructure wiu. It's not a big deal)
My biggest argument is time. We are very very slow. Mostly because I'm not coding quick and high-quality code))

2022-06-11 15:49 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +		try {
Yes, you're right. Fixed for the Object.assign)
But as for JsonUtils.ts - we don't need it now. I can't imagine other json utils now. If we have any more - we can quickly restructure wiu.
I guess it's better to have single module with 100 functions than have 100 module with 1 function each.

2022-06-11 15:53 UTC, roman-timo commented on frontend/utils/ServerUtils.ts
>  	}
no particular reason. We can move it to WIU haha to add your arguments on restructuring more weight :)))

2022-06-11 15:55 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +	};
> It will also mean new imports

What is the harm of few more imports? 

> I can't see what other functions would be added into wiu, can't even imagine

You said "I think wiu - is a nice tool for all functions with graph and UI of graph ". So basically you want to dump all the UI logic of graph here. It is super broad scope, and It will be a big hell of a mess. 

> Also, once this is needed - we can easily restructure wiu. It's not a big deal)

Lol! It is already needed. We are already mixing different logic and code becomes less structured and less readable. UI logic for the graph  deserves its own file

> My biggest argument is time

There is almost no time-costs in structuring code. But there will be "hidden" time price for navigating in less readable code

2022-06-11 15:58 UTC, AlexFreik commented on frontend/utils/WebInterfaceUtils.ts
> +		try {
> I can't imagine other json utils now

It is the next step. I'll add quite a bit of a logic there since i refactored backend to have `uidata` containing positions and etc. Also we will put there all the extractNodes, extractEdges , etc

2022-06-11 22:03 UTC, roman-timo commented on frontend/components/document/Navbar.tsx
> +	const removeRecent = (evt: React.MouseEvent<HTMLDivElement>) => {
fixed

2022-06-11 22:04 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +	};
fixed

2022-06-11 22:04 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +		try {
rebuilt into JsonUtils

2022-06-11 22:05 UTC, roman-timo commented on frontend/utils/ServerUtils.ts
>  	}
fixed

2022-06-12 05:58 UTC, AlexFreik commented on frontend/components/document/DnDFlow.tsx
> +		[wiu.graph.name, wiu.setUiNodes],
what it have to do with `wiu.graph.name`?

2022-06-12 07:34 UTC, roman-timo commented on frontend/styles/Block.module.css
> +}
fixed

2022-06-12 07:34 UTC, roman-timo commented on frontend/components/document/Navbar.tsx
> +		: styles.fileMenu + ' ' + styles.fileMenuHidden;
fixed

2022-06-12 07:36 UTC, roman-timo commented on frontend/utils/WebInterfaceUtils.ts
> +			this.saveGraphToLocalStorage();
do you want to add new useEffect into dndFlow and remove it from wiu?

2022-06-12 07:37 UTC, roman-timo commented on frontend/components/document/DnDFlow.tsx
> +		[wiu.graph.name, wiu.setUiNodes],
not sure... I thought some logic behind this, but now I can't reproduce)
removed

2022-06-12 09:47 UTC, AlexFreik approved these changes
good

2022-06-12 09:51 UTC, merged