introduce SelectedNode
atlas-blocks/atlas pull request #55
Opened 2022-06-15 08:06 UTC by roman-timo

2022-06-15 10:30 UTC, AlexFreik requested changes

2022-06-15 10:30 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +	data.node.content = `[JSON3.write(${srcSelect}[${selected + 1}]), JSON3.write(${srcSelect})]`;
no) It is better not to do `JSON3.write(${srcSelect})`, since it is better to allow Julia to use its representation. For example, if it is array of functions, then what will you get here? But with Julia you will get a nice string representation

2022-06-15 10:30 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +					value={srcSelect}
As we discussed earlier, it is better to not use such short forms like `src`. Just use `source`, it is not much longer, but more readable

2022-06-15 11:53 UTC, AlexFreik requested changes

2022-06-15 11:53 UTC, AlexFreik commented on frontend/components/document/PropsPanel.tsx
> +		wiu.selectedNode,
what is the reason for this changes?

2022-06-15 15:57 UTC, AlexFreik requested changes

2022-06-17 19:41 UTC, roman-timo commented on frontend/components/document/PropsPanel.tsx
> +		wiu.selectedNode,
i guess this is outdated.

2022-06-17 19:41 UTC, roman-timo commented on frontend/utils/AtlasGraph.ts
> +	public setSelectedOption: React.Dispatch<React.SetStateAction<number>>;
got rid of it

2022-06-17 19:42 UTC, roman-timo commented on frontend/utils/AtlasGraph.ts
> +export class SelectNode extends ExpressionNode {
will be fixed with next comit)

2022-06-28 16:23 UTC, merged