graphics-module
atlas-blocks/atlas pull request #64
Opened 2022-06-24 10:03 UTC by roman-timo

2022-07-15 21:46 UTC, AlexFreik requested changes

2022-07-15 21:46 UTC, AlexFreik commented on frontend/utils/JsonUtils.ts
> +	public static extractNodes(nodes: Record<string, never>[]): AtlasNode[] {
Rom) Do you know what `never` means?

2022-07-15 21:46 UTC, AlexFreik commented on frontend/styles/main.module.css
> +.centralField {
maybe `.tab` ?

2022-07-15 21:46 UTC, AlexFreik commented on frontend/styles/main.module.css
> +	display: none !important;
what was the reason for this?

2022-07-15 21:46 UTC, AlexFreik commented on frontend/pages/document.tsx
> +				<FieldControl />
Maybe we can name it `Tabs` ?

2022-07-16 18:20 UTC, roman-timo commented on frontend/utils/JsonUtils.ts
> +	public static extractNodes(nodes: Record<string, never>[]): AtlasNode[] {
This is just what Lint suggested)) I just took first choice))
What is neede here?

2022-07-16 18:20 UTC, roman-timo commented on frontend/styles/main.module.css
> +.centralField {
Tab - is a tab on top of the Field. Field - is the big thing in the Center of the screen)

2022-07-16 18:23 UTC, roman-timo commented on frontend/styles/main.module.css
> +	display: none !important;
There are other components inside which use display: none or “not-none”. Thus they overwrite this state and become visible when they should all be hidden. 
so, I need to force this display state to all the children.

2022-07-16 18:24 UTC, roman-timo commented on frontend/pages/document.tsx
> +				<FieldControl />
See cmnt above :)
We might call it ‘Panel’, but this will mix with other Panels we already have.

2022-07-16 19:17 UTC, roman-timo commented on frontend/styles/main.module.css
> +.centralField {
Maybe Canvas?

2022-07-17 07:30 UTC, AlexFreik commented on frontend/utils/JsonUtils.ts
> +	public static extractNodes(nodes: Record<string, never>[]): AtlasNode[] {
Lint suggested many things, you can read them

<img width="858" alt="Screenshot 2022-07-17 at 10 30 21" src="https://user-images.githubusercontent.com/61039123/179388532-2fcc6364-b79f-4fcb-85dc-ecc22d4434c9.png">

2022-07-17 07:32 UTC, AlexFreik commented on frontend/styles/main.module.css
> +.centralField {
> Tab - is a tab on top of the Field. Field - is the big thing in the Center of the screen)

oh i see.

Maybe TabSection?

2022-07-17 08:44 UTC, roman-timo commented on frontend/utils/JsonUtils.ts
> +	public static extractNodes(nodes: Record<string, never>[]): AtlasNode[] {
Can you pls make it while I'm on mobile)

2022-07-17 08:48 UTC, roman-timo commented on frontend/styles/main.module.css
> +.centralField {
tab is a small tab. Even tabSection is a set of Tabs :))

Maybe 
- Ground
- Plot
- Place
- Garden
- Plate
- WorkingArea
- Main
- MainSection
- Screen
- Canvas
- Field

I thought Field or Canvas would be nice, coz you can 'Drop something to a Field/Canvas'

2022-08-20 16:04 UTC, closed without merging

2022-08-20 16:05 UTC, roman-timo commented
outdated due to newest version of desmos in another branch