Object node fixes
atlas-blocks/atlas pull request #66
Opened 2022-06-26 19:57 UTC by AlexFreik

2022-06-26 20:08 UTC, AlexFreik commented on frontend/components/document/props/ObjectNodeBuilder.tsx
> -				}),
It is hard to read. It is better to use new variable for obscure conditions like `event.target.id.slice(0, 1) === '0'`

2022-06-26 20:08 UTC, AlexFreik commented on frontend/components/document/props/ObjectNodeBuilder.tsx
> -						id={'0' + index.toString()}
Such short `id` is not very safe. it can easily be clashed with some other `id`

2022-06-26 20:08 UTC, AlexFreik commented on frontend/components/document/props/ObjectNodeBuilder.tsx
> -						}
:)

2022-06-26 20:08 UTC, AlexFreik commented on frontend/components/document/DnDFlow.tsx
> -	}
you forgot to run make pretty

2022-06-26 20:08 UTC, AlexFreik commented on frontend/utils/AtlasGraph.ts
> -	public objProperties: string[][];
it is bettr to use more specific type `[string, string][]`

2022-06-26 20:08 UTC, AlexFreik commented on frontend/utils/AtlasGraph.ts
> +
you forgot about uidata, and created zillion of states again

2022-06-26 20:08 UTC, AlexFreik commented on frontend/components/document/props/ObjectNodeBuilder.tsx
> -	console.log(inputState.state);
you forgot to review your changes

2022-06-26 20:08 UTC, AlexFreik commented on frontend/components/document/props/ObjectNodeBuilder.tsx
> -				{objProperties.map((property: string[], index: number) =>
You don't need to specify types here. Typescript already knows type of `objProperties` so it can infer types of `property` and `index`

2022-06-27 08:55 UTC, roman-timo requested changes
Ok, the code looks better) But this didn't fix the issue with the same properties of two ObjectNodes

2022-06-27 09:07 UTC, roman-timo requested changes

2022-06-27 09:07 UTC, roman-timo commented on frontend/utils/AtlasGraph.ts
> +		this.objProperties.forEach((prop) => (newContent += prop[0] + '=>' + prop[1] + ','));
I think prop[0] should be inside " ", the key is always a name of the property

2022-06-28 15:45 UTC, AlexFreik commented on frontend/utils/AtlasGraph.ts
> +		this.objProperties.forEach((prop) => (newContent += prop[0] + '=>' + prop[1] + ','));
oke, we can do it this way

2022-06-28 16:18 UTC, merged