desmos node & improved flow logic
atlas-blocks/atlas pull request #85
Opened 2022-07-23 08:58 UTC by AlexFreik

2022-07-25 14:32 UTC, roman-timo requested changes
Uhh, this code I can't name as simple and straightforward. Maybe Desmos doesn't worth it.

2022-07-25 14:32 UTC, roman-timo commented on frontend/src/graph/nodes/DesmosNode.ts
> +		this.content = '';
Why we need to sent this content here '' ?

2022-07-25 14:32 UTC, roman-timo commented on frontend/src/kernels/JuliaExecuter.ts
> +				});
maybe the former single line was better..

2022-07-25 14:32 UTC, roman-timo commented on frontend/src/utils/AtlasWindowUtils.ts
> +export default class AtlasWindowUtils {
Maybe we don't even need this AWU at all.
Just add a 'flows' array into wiu and a method .setFlows. That's it. It's gonna be simple. We don't need extra 50 lines of code. No real need for public methods .addFlow and .removeFlow

Same concept as React-Flow: they just made nodes array. Everything else is made locally, not as a global method in the class.

Why we ever need a clearFlows method? you don't use it anywhere, so why?

And also remember - this is just for one f**** Desmos...! There's a whole bunch of classes and tens of methods. Does Desmos worth it really?

I think we can park tis AWU thing and just let UiAtlasWindow do the job by itself, using a simple array of Flows.

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/UiAtlasWindow.tsx
> +						key={flow.getId()}
> what is flow.getId? How it is different from flow.getName?

id must be unique, name is not

> Why they called getName if it is just a name of the flow? why it is a function, but not a property?

`Flow` class doesn't have property name, only abstract `getName()`

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/UiAtlasWindow.tsx
> +						{React.createElement(uiFlowTypes[flow.constructor.name], {
Good question) When you write `< MyComponent />` react actually renders it into ` React.createElement(MyComponent, {})`. So this form is just a shortcut

And since we store component in a dictionary, i couldnt manage to use this short form. You can try to do it, if you want

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/flows/UiAtlasGraphFlow.tsx
> +				}
because it will work only for desmos node in this case. This implementation is more general and will work for every typo of node

and it not much more complex

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/flows/UiAtlasGraphFlow.tsx
> +					console.log('bbb');
forgot to remove it though

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +declare global {
Didn't you had a typescirpt error?

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +		calculatorElement!.innerHTML = '';
i'll add a comment

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +		calculatorElement!.innerHTML = '';
yes, it is very important, otherwise desmos wouldn't change div with plots on rerender

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +			latex: flow.node.getContent(),
Some nodes have special setter for the content, so I made content protected field so people don't change it accdetaly.
So `node.content = newContent` is bad, we should use `node.setContent(content)`.

That is why we are also using `getContent`

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +		if (awu.getSelectedFlow() !== flow) return;
oh yeah, it is a bit confusing right now. i need to change names (`awu.getSelectedFlow() !== awu.selectedFlow`)

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +		if (wiu.selectedNode !== flow.node) wiu.setSelectedNode(flow.node);
true, haha

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +	}, [wiu.selectedNode, awu.selectedFlow]);
1) i believe we reload every component when we select some node, because `wiu.selectedNode` is a part of `Home` and Home with everything inside gets reloaded
 
Actually maybe we should change it and move `SelectedNode` creation into `AtlasGraphFlow`.

2) we don't reload whole desmos thing, since i have the check in the begining
`if (awu.getSelectedFlow() !== flow) return;` so it just exits if we are not inside this flow.

2022-07-25 15:35 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +			<Script
> I think 3 desmos scripts will remain

hell no))) browser loads script only once, as you said, it is not efficient to load it twice, haha) you can check networks

2022-07-25 15:35 UTC, AlexFreik commented on frontend/src/graph/nodes/DesmosNode.ts
> +		this.content = '';
god point, i'll clean it

2022-07-25 15:35 UTC, AlexFreik commented on frontend/src/graph/nodes/ContentNode.ts
> +	protected content = '';
Why i think it is nice to make it protected i explained above.

I'm using Java style here. In Java you normally make everything `private`/`protected`, and have getters and setters for them. It is not `_content` since it is easier to export it into json this way, because i don't want it be `_content` inside json.

2022-07-25 15:35 UTC, AlexFreik commented on frontend/src/flows/Flow.ts
> +export default abstract class Flow {
What do you mean? This class is important because it is Flow abstraction, like `AtlasNode`. Where do you want me to put it?

2022-07-25 15:35 UTC, AlexFreik commented on frontend/src/flows/AtlasGraphFlow.ts
> +export default class AtlasGraphFlow extends Flow {
I think we should discuss this design in a call. this concept may be a bit long to explain here

2022-07-25 15:44 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
>  			{resultWrapper(renderResult(node.getResult()))}
> > 3 divs one into another just to show a result
> 
> why is this a problem?

If we can make it 1 div, why we need a pack of 3?

2022-07-25 15:45 UTC, roman-timo commented on frontend/components/document/UiAtlasWindow.tsx
> +export default function AtlasWindow(): JSX.Element {
File name. why it is Ui in the beginning?

2022-07-25 15:49 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +			{blockWrapper(node, <div>{contentWrapper(node.getContent())}</div>)}
yes, need to clean some mess

2022-07-25 15:49 UTC, roman-timo commented on frontend/components/document/UiAtlasWindow.tsx
> +						{React.createElement(uiFlowTypes[flow.constructor.name], {
ok. let's use it in the short form. So the style of all our addings of new components will be the same across all modules

2022-07-25 15:52 UTC, roman-timo commented on frontend/src/flows/Flow.ts
> +export default abstract class Flow {
I mean why we need Flow as a class?

2022-07-25 15:54 UTC, roman-timo commented on frontend/src/graph/nodes/ContentNode.ts
> +	protected content = '';
I can't find was about protected mentioned above..

2022-07-25 19:03 UTC, roman-timo requested changes
some comments

2022-07-25 19:03 UTC, roman-timo commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +			<Script
Maybe I didn't tell this right..)
I mean when you add desmos Node 3 times, you load script 3 times and get 3 divs with calculator and you get a window.Desmos object (or maybe 3 of them, not sure). 

What will happen if you remove from the AtlasFlow all these 3 nodes? 3 Scripts, 3 divs, and window.Desmos - stay in memory. (I'm not sure about divs though...). 
Even if you not render them anymore in map - they still in memory. You can check, window.Desmos remains after you kill last desmos.

2022-07-25 19:03 UTC, roman-timo commented on frontend/components/document/flows/UiJupyterFlow.tsx
>  	const jupyterNotebookRef = React.useRef<HTMLIFrameElement>(null);
No no., it gets more code and a lot of text. useRef - is way better than React.useRef
less code - better read.

2022-07-27 11:50 UTC, AlexFreik commented on frontend/components/document/UiAtlasWindow.tsx
> +						{React.createElement(uiFlowTypes[flow.constructor.name], {
<uiFrameTypes[flow.getType()] className={styles.flow}>

2022-07-27 12:17 UTC, AlexFreik commented on frontend/components/document/flows/UiAtlasGraphFlow.tsx
> +				}
ujjj

2022-07-27 18:58 UTC, AlexFreik commented on frontend/components/document/UiAtlasWindow.tsx
> +export default function AtlasWindow(): JSX.Element {
done

2022-07-27 18:58 UTC, AlexFreik commented on frontend/components/document/UiAtlasWindow.tsx
> +						{React.createElement(uiFlowTypes[flow.constructor.name], {
done

2022-07-27 18:58 UTC, AlexFreik commented on frontend/components/document/flows/UiAtlasGraphFlow.tsx
> +				}
done (moved `onDropMap` to wiu)

2022-07-27 18:58 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +		calculatorElement!.innerHTML = '';
done

2022-07-27 18:58 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +		if (awu.getSelectedFlow() !== flow) return;
done

2022-07-27 18:58 UTC, AlexFreik commented on frontend/components/document/flows/UiDesmosFlow.tsx
> +		if (wiu.selectedNode !== flow.node) wiu.setSelectedNode(flow.node);
done

2022-07-27 18:58 UTC, AlexFreik commented on frontend/components/document/flows/UiJupyterFlow.tsx
>  	const jupyterNotebookRef = React.useRef<HTMLIFrameElement>(null);
done

2022-07-27 18:58 UTC, AlexFreik commented on frontend/components/document/flows/UiJupyterFlow.tsx
>  	React.useEffect(() => {
done

2022-07-27 18:58 UTC, AlexFreik commented on frontend/src/graph/nodes/DesmosNode.ts
> +		this.content = '';
done

2022-07-27 18:58 UTC, AlexFreik commented on frontend/src/kernels/JuliaExecuter.ts
> +				});
done

2022-07-27 20:26 UTC, roman-timo submitted a review, later dismissed
f***ng desmos finally :)

2022-07-27 20:31 UTC, roman-timo approved these changes
Good

2022-07-27 20:34 UTC, merged