User auth
atlas-blocks/atlas pull request #95
Opened 2022-08-01 22:49 UTC by roman-timo

2022-08-01 23:19 UTC, roman-timo commented
I'm not sure about pkg.json... and didn't fixed proxy in nginx.config. maybe you can do this ))

2022-08-05 12:18 UTC, AlexFreik commented on frontend/pages/api/login.ts
> +import bcrypt from 'bcryptjs';
this gives error. please fix

2022-08-05 12:18 UTC, AlexFreik commented on frontend/src/utils/AtlasUser.js
> +import { Schema, model, models, Types } from 'mongoose';
should be `.ts`

2022-08-05 12:18 UTC, AlexFreik commented on frontend/src/utils/connectMongo.js
> +import mongoose from 'mongoose';
should be `.ts`

2022-08-05 12:18 UTC, AlexFreik commented on reverse_proxy/nginx.conf
> +#         }
please revert this back) you don't need to comment part with `/_next/webpack-hmr`

2022-08-05 12:25 UTC, AlexFreik commented on frontend/pages/_middleware.ts
> +		atlasUserToken = JSON.parse(decodeURIComponent(request.cookies['AtlasUser']));
why not just user?

2022-08-05 12:57 UTC, AlexFreik requested changes

2022-08-05 12:57 UTC, AlexFreik commented on frontend/pages/_middleware.ts
> +	if (request.cookies['AtlasUser'])
You are using magic variable `'AtlasUser'` in many places. Give it a name and put it inside StorageUtils or something like this.

2022-08-05 12:57 UTC, AlexFreik commented on frontend/src/utils/AuthAPIFetcher.ts
> +export default async function AuthAPIFetcher(url: string, body: any) {
name `AuthAPIFetcher` look like it is a class. It should be smth like `fetchForAuth` to look like a function

2022-08-05 12:57 UTC, AlexFreik commented on frontend/src/utils/AuthAPIFetcher.ts
> +	return response;
so this function returns data or object with json or string with error? 
1. I think you should put this function in the `ServerUtils`, it doesn't deserve a sepparate file, plus we have (had) similar funcs there
2. it is a bit confusing what this function may return. Maye it is better to return dictionary `{error, data}`? where `error` or `data` can be null

2022-08-05 13:03 UTC, roman-timo commented on frontend/pages/_middleware.ts
> +		atlasUserToken = JSON.parse(decodeURIComponent(request.cookies['AtlasUser']));
It sits in browser cookies. Should be some identifier it is Atlas's cookie

2022-08-05 15:35 UTC, roman-timo commented on frontend/pages/api/login.ts
> +import bcrypt from 'bcryptjs';
fixed

2022-08-05 15:36 UTC, roman-timo commented on frontend/src/utils/AtlasUser.js
> +import { Schema, model, models, Types } from 'mongoose';
fixed

2022-08-05 15:36 UTC, roman-timo commented on frontend/src/utils/connectMongo.js
> +import mongoose from 'mongoose';
fixed

2022-08-05 15:36 UTC, roman-timo commented on reverse_proxy/nginx.conf
> +#         }
done

2022-08-05 15:36 UTC, roman-timo commented on frontend/pages/_middleware.ts
> +	if (request.cookies['AtlasUser'])
fixed. Moved to StorageUtils.

2022-08-05 15:37 UTC, roman-timo commented on frontend/src/utils/AuthAPIFetcher.ts
> +export default async function AuthAPIFetcher(url: string, body: any) {
left the name authAPIFetcher cuz that's what it does :)
but moved to ServerUtils

2022-08-05 15:38 UTC, roman-timo commented on frontend/src/utils/AuthAPIFetcher.ts
> +	return response;
1) Moved to ServerUtils
2) I think the "response" is a right return. Error will be given inside response.message.

2022-08-05 16:01 UTC, AlexFreik commented on frontend/pages/_middleware.ts
> +		atlasUserToken = JSON.parse(decodeURIComponent(request.cookies['AtlasUser']));
Every domain have it's own cookies (if person opens a new tab with different website like `example.com`, then he will have different cookies there, afaik. So what is the issue?

2022-08-05 16:04 UTC, AlexFreik requested changes

2022-08-05 16:04 UTC, AlexFreik commented on frontend/src/utils/StorageUtils.ts
> +	public static readonly AtlasCookieKey = 'AtlasUser';
Usually classes have name in `PascalCase`. Constants usually have either `camelCase` like normal variables or `THIS_CASE`

2022-08-05 16:04 UTC, AlexFreik commented on frontend/pages/api/login.ts
> +		setCookie({ res }, 'AtlasUser', JSON.stringify({ username: user.username, token }), {
you are still using `'AtlasUser'` here)

2022-08-05 16:04 UTC, AlexFreik commented on frontend/pages/api/logout.ts
> +		setCookie({ res }, 'AtlasUser', '', { maxAge: -1, path: '/' });
'AtlasUser' ))

2022-08-05 16:04 UTC, AlexFreik commented on frontend/src/utils/AtlasUser.ts
> +const AtlasUser = models.AtlasUser || model('AtlasUser', schema);
'AtlasUser' )))

2022-08-05 16:06 UTC, AlexFreik commented on frontend/components/document/Navbar.tsx
>  import React, { ChangeEvent, useEffect, useRef, useState } from 'react';
Have you tried to revert .`cjs` to `.js` ?

2022-08-05 16:06 UTC, AlexFreik commented on frontend/pages/_middleware.ts
> +	if (request.cookies['AtlasUser'])
Great, thanks)

2022-08-05 16:08 UTC, AlexFreik commented on frontend/src/utils/AuthAPIFetcher.ts
> +export default async function AuthAPIFetcher(url: string, body: any) {
No, authAPIFetcher is not what it does, but who is it. Name of a function should be an action like `getThis` `doThat` `resolveItWhenABC`. In you case it is what it is, like `Cat` or `Dog` or `Executer`, it is more sutable to an entity

2022-08-05 16:09 UTC, AlexFreik commented on frontend/src/utils/AuthAPIFetcher.ts
> +export default async function AuthAPIFetcher(url: string, body: any) {
But if you really like this name, you can just resolve this, i don't care this much

2022-08-05 16:11 UTC, AlexFreik commented on frontend/src/utils/AuthAPIFetcher.ts
> +	return response;
> Error will be given inside response.message

what do you mean? You have a line
```ts
response = e.message;
```
And also you initialise `resoponse` is a string, not object

2022-08-05 16:43 UTC, roman-timo commented on frontend/pages/_middleware.ts
> +		atlasUserToken = JSON.parse(decodeURIComponent(request.cookies['AtlasUser']));
I think there's no problem with name 'AtlasUser'

2022-08-05 16:44 UTC, roman-timo commented on frontend/src/utils/AuthAPIFetcher.ts
> +export default async function AuthAPIFetcher(url: string, body: any) {
ok. renamed to fetchAuth

2022-08-05 16:45 UTC, roman-timo commented on frontend/src/utils/AuthAPIFetcher.ts
> +	return response;
I can't t define the right initial value as response uncertain opbject. I could give it a 'null', but it's the same as ''

2022-08-05 16:45 UTC, roman-timo commented on frontend/src/utils/StorageUtils.ts
> +	public static readonly AtlasCookieKey = 'AtlasUser';
Atlas should be started with capital letter :)

2022-08-05 16:45 UTC, roman-timo commented on frontend/pages/api/login.ts
> +		setCookie({ res }, 'AtlasUser', JSON.stringify({ username: user.username, token }), {
fixed

2022-08-05 16:46 UTC, roman-timo commented on frontend/pages/api/logout.ts
> +		setCookie({ res }, 'AtlasUser', '', { maxAge: -1, path: '/' });
fixed

2022-08-05 16:48 UTC, roman-timo commented on frontend/src/utils/AtlasUser.ts
> +const AtlasUser = models.AtlasUser || model('AtlasUser', schema);
here is different. It is a model name inside MongoDB. We could declare a special constant for this name inside this AtlasUser module, but I think it is ambiguous in this case.

2022-08-05 16:49 UTC, roman-timo commented on frontend/components/document/Navbar.tsx
>  import React, { ChangeEvent, useEffect, useRef, useState } from 'react';
yes. it gives an error during build of container.


frontend       | error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
frontend       | ReferenceError: module is not defined in ES module scope
frontend       | This file is being treated as an ES module because it has a '.js' file extension and '/app/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

2022-08-05 17:15 UTC, AlexFreik commented on frontend/pages/_middleware.ts
> +		atlasUserToken = JSON.parse(decodeURIComponent(request.cookies['AtlasUser']));
Oke, if you like it it's fine. I just thought it can be too verbose) You can resolve it

2022-08-05 17:16 UTC, AlexFreik commented on frontend/src/utils/AuthAPIFetcher.ts
> +export default async function AuthAPIFetcher(url: string, body: any) {
Great, thanks)

2022-08-05 17:20 UTC, AlexFreik commented on frontend/src/utils/AuthAPIFetcher.ts
> +	return response;
1. Maybe you have a mistake here. You can't do `response.message` because you are doing `response = e.message;` Maybe you want `response.message = e.message` ?
2. hell no, `null` is not the same as `''`))) It is better for the reader if variable doesn't change it's type. So you can have
```ts
let response = {body: null, message: null};
```
for example

2022-08-05 17:24 UTC, AlexFreik commented on frontend/src/utils/StorageUtils.ts
> +	public static readonly AtlasCookieKey = 'AtlasUser';
Atlas is just a word, it is not a Language Lessons, it's programming. Here we care about readability and don't confuse reader without a reason) Even microsoft named their github with a lovercase letter, why are you feeling so important?
<img width="427" alt="Screenshot 2022-08-05 at 20 23 09" src="https://user-images.githubusercontent.com/61039123/183129175-5ad3259a-876e-4aad-9076-0c19d8555aa6.png">

2022-08-05 17:27 UTC, AlexFreik commented on frontend/src/utils/AtlasUser.ts
> +const AtlasUser = models.AtlasUser || model('AtlasUser', schema);
You can think it looks stupid, but it would be better to add one more line in this case:
```ts
const mongoModelName = 'AtlasUser';
const AtlasUser = models.AtlasUser || model(mongoModelName, schema);
```

2022-08-05 18:18 UTC, roman-timo commented on frontend/src/utils/AuthAPIFetcher.ts
> +	return response;
ok. got it. fixed.

2022-08-05 18:20 UTC, roman-timo commented on frontend/src/utils/StorageUtils.ts
> +	public static readonly AtlasCookieKey = 'AtlasUser';
I don't think that is so much important taking into account our non-perfect code. It is good to have this rule, but this is not extreme mandatory condition and not mission critical at all. The name of the constant describes itself pretty well. I think we can leave it like this.

2022-08-05 18:20 UTC, roman-timo commented on frontend/src/utils/AtlasUser.ts
> +const AtlasUser = models.AtlasUser || model('AtlasUser', schema);
ok. fixed.

2022-08-05 21:04 UTC, AlexFreik commented on frontend/src/utils/StorageUtils.ts
> +	public static readonly AtlasCookieKey = 'AtlasUser';
> The name of the constant describes itself pretty well

Well, i would say it's not very clear what kind of cookie key it is (from name). Maybe `userCookieKey` is better?

Or `AtlasUserCookieKey` if you would love to have Atlas in the name

2022-08-06 14:49 UTC, roman-timo commented on frontend/src/utils/StorageUtils.ts
> +	public static readonly AtlasCookieKey = 'AtlasUser';
I think AtlasUser is good enough. Don't really feel we need  add Cookie inside Cookies. Anyway it is only Cookies there, what else could be there..
Also Key it is anyway a key, nothing could be other than a key.

2022-08-06 16:46 UTC, AlexFreik requested changes

2022-08-06 16:46 UTC, AlexFreik commented on frontend/pages/login.tsx
> +					{isRegistration && <button onClick={registerHandler}>register</button>}
usually it is log in and sign up. You probably used "register" because you are russian

2022-08-06 16:46 UTC, AlexFreik commented on frontend/pages/login.tsx
> +					{isRegistration && <button onClick={registerHandler}>register</button>}
`Sign Up` button disappears after incorrect password combination

<img width="568" alt="Screenshot 2022-08-06 at 19 43 14" src="https://user-images.githubusercontent.com/61039123/183258238-33323b64-4b37-4e7e-9cfe-812e02608950.png">

2022-08-06 16:55 UTC, roman-timo commented on frontend/pages/login.tsx
> +					{isRegistration && <button onClick={registerHandler}>register</button>}
this is how it works. You should refresh the page to see this registration again

2022-08-06 17:06 UTC, roman-timo commented on frontend/pages/login.tsx
> +					{isRegistration && <button onClick={registerHandler}>register</button>}
hahaha, I'm glad you didn't call me Dutch :))))

(seriously, I thought about it and used it intentionally)

2022-08-06 17:07 UTC, roman-timo commented on frontend/src/utils/StorageUtils.ts
> +	public static readonly AtlasCookieKey = 'AtlasUser';
fixed

2022-08-06 17:10 UTC, AlexFreik commented on frontend/pages/login.tsx
> +					{isRegistration && <button onClick={registerHandler}>register</button>}
oke

2022-08-06 17:38 UTC, AlexFreik commented
After you click `register` this button should became grey and not active. Otherwise 
1. user can click 20 times in these 10 seconds while server processing request
2. it is kind of unintuitive what is happening

<img width="518" alt="Screenshot 2022-08-06 at 20 34 50" src="https://user-images.githubusercontent.com/61039123/183259829-8aa42bb1-75b3-47f2-a493-318c5f89271b.png">

2022-08-06 17:56 UTC, AlexFreik requested changes

2022-08-06 17:56 UTC, AlexFreik commented on frontend/pages/login.tsx
> +					{isRegistration && <button onClick={registerHandler}>register</button>}
We need to disable this button after user clicks and before server replies. Otherwise nothing changes and it is confusing
<img width="453" alt="Screenshot 2022-08-06 at 20 50 22" src="https://user-images.githubusercontent.com/61039123/183260250-c0843066-1b76-41b8-a648-a9f1404c3811.png">


And same for the login button

2022-08-06 17:56 UTC, AlexFreik commented on frontend/components/document/Navbar.tsx
> +					<label className={styles.logoutLabel}>logout</label>
It is very unintuitive) it should be name of a user instead of logout.
<img width="81" alt="Screenshot 2022-08-06 at 20 52 45" src="https://user-images.githubusercontent.com/61039123/183260400-7c9eff34-bdc2-4ae5-997b-5c6b860fc46d.png">
Also when you click on the user profile pic then there should be drop down with sign out option. Like on GitHub
<img width="216" alt="Screenshot 2022-08-06 at 20 54 33" src="https://user-images.githubusercontent.com/61039123/183260406-c90f2d7b-d494-479e-af74-37d342851281.png">

2022-08-06 17:56 UTC, AlexFreik commented on frontend/components/document/Navbar.tsx
> +					<label className={styles.logoutLabel}>logout</label>
It is a bit more work, but it will look much better

2022-08-06 17:57 UTC, AlexFreik commented on frontend/pages/login.tsx
> +					{isRegistration && <button onClick={registerHandler}>register</button>}
well, it is unintuitive) usually it is done different

<img width="515" alt="Screenshot 2022-08-06 at 20 09 10" src="https://user-images.githubusercontent.com/61039123/183260454-0a7986f4-9c31-4c5c-a24c-f80234292be3.png">

2022-08-06 18:14 UTC, roman-timo commented on frontend/pages/login.tsx
> +					{isRegistration && <button onClick={registerHandler}>register</button>}
Yes, would be great to have reset your password option. It is not there yet.

2022-08-06 18:17 UTC, roman-timo commented on frontend/pages/login.tsx
> +					{isRegistration && <button onClick={registerHandler}>register</button>}
Yes, good point. I didn't do "loading" state yet, and I guess it will require some efforts. Probably Context to cover this logic in several modules. Don't know yet. 

Maybe we can do this in the next release ;)

2022-08-06 18:21 UTC, roman-timo commented on frontend/components/document/Navbar.tsx
> +					<label className={styles.logoutLabel}>logout</label>
For sure you're right. Why do u think I added this ugly text under the nice button? :))) - it's just because I started to make context menu under this button, but then stuck with that for 3+ hours with all the styles and alignment etc.. and thought that was enough for me :))

I left the profile menu for the next time :)

2022-08-07 10:06 UTC, AlexFreik approved these changes

2022-08-08 06:36 UTC, merged