Graph module
atlas-blocks/atlas pull request #99
Opened 2022-08-07 23:29 UTC by AlexFreik

2022-08-08 07:04 UTC, roman-timo commented
> 1. You can read why I decided to replace all
>    ```ts
>    import something from ...
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    with
>    ```ts
>    import { something } from ...
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    https://stackoverflow.com/questions/33305954/typescript-export-vs-default-export
> 2. I decided to refactor graph nodes right now, because it will be harder in the future when actual users start using the graph
>    
>    * moved almost all `julia` logic inside `JuliaExecuter` from graph
>    * nodes like `SelectionNode` and `ObjectNode` doesn't have useless `content` property anymore. It was duplicating data and I have to do hustle and bustle with setters and etc


I don't really get it.... why did you change default exports for named exports. In components like NavBar, for example..

2022-08-08 19:10 UTC, roman-timo requested changes
part 1

2022-08-08 19:10 UTC, roman-timo commented on frontend/components/blocks/UiNode.tsx
> +			wiu.refreshUiElements();
Would be best not to recalculate immediately whole graph when you add this file. Maybe it is possible without full refresh?

2022-08-08 19:10 UTC, roman-timo commented on frontend/components/document/PropsPanel.tsx
> +		ignored: new InputState('ignored', useState<string>('')),
hm.. I tried really to understand this... But why we need to ignore something explicitely when it doesnt exists? Why we need to pass "ignored" if theres is not input?
Is this a special case for ObjectNode only?

2022-08-08 19:10 UTC, roman-timo commented on frontend/components/document/PropsPanel.tsx
> +			if (nodeInput.inputState.name == 'ignored') continue;
Maybe just describe and exception when we don't need an InputState? 
if XXX  continue...

Still not quite quite sure what inputState does and why it is so complicated :))   (after 10th time I watch this)

2022-08-08 22:16 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +			}
good idea, fixed

2022-08-08 22:20 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +			wiu.refreshUiElements();
well, i think that refresh is very cheap, so it is not an issue. but i think it looks ugly anyway. so I fixed it (by adding auto-generated id to nodes)

2022-08-08 22:20 UTC, AlexFreik commented on frontend/components/document/PropsPanel.tsx
> +		ignored: new InputState('ignored', useState<string>('')),
fixed it)

2022-08-08 22:21 UTC, AlexFreik commented on frontend/components/document/PropsPanel.tsx
> +			if (nodeInput.inputState.name == 'ignored') continue;
yeah, PropsPanel is cursed) I'm sorry

2022-08-08 22:24 UTC, AlexFreik commented on frontend/components/blocks/UiNode.tsx
> +		FileUtils.getFileContentString(event.target.files[0], (content: string) => {
IDK, FileUtils.getContent have callback because operation of reading file is async. I don't know how to improve it rn. Also i just copied it from `FileBlock` so it is not a problem for this pr :)

2022-08-09 06:58 UTC, roman-timo requested changes
finished with nodes part

2022-08-09 06:58 UTC, roman-timo commented on frontend/src/graph/nodes/ScriptNode.ts
> +	providerNames: string[] = [];
Can't find the usage for this.. what it used for?

2022-08-09 06:58 UTC, roman-timo commented on frontend/src/graph/nodes/ScriptNode.ts
> +	public response: ExecutionResponse | null = null;
Why ExecutionResponse can be null? I thought response from Julia Kernel is always something - either error or nothing.

2022-08-09 06:58 UTC, roman-timo commented on frontend/src/graph/nodes/ScriptNode.ts
> +		return this.response === null ? null : this.response.error;
1. If I understood correctly the ExecutionResponse cannot be null. It can e minimum {result: [], error: null).
2. We don't need to check for the error. anyway it is either null (default state at creation) or something {value, traceback}.

2022-08-09 06:58 UTC, roman-timo commented on frontend/src/graph/nodes/ScriptNode.ts
> +	public getErrorString(): string {
Depending on the previouse comment.. (error/response cannot be null).. if that's true :
better to have this logic right at the arrival of error, i.e at execution point. We we need to pull that situation into a class and crate a special hadle method for this.
I suppose if all exeptions would be hadled at the point of arrival, we will just need one method in the lass - 
public getError(): string. Instead of three error-hadling methods right here.

2022-08-09 06:58 UTC, roman-timo commented on frontend/src/kernels/execution.ts
> +	'text/plain'?: string;
If this is anyway string, why we need to separate them?
Why just the .result could not be a type string?

2022-08-09 06:58 UTC, roman-timo commented on frontend/src/graph/nodes/ScriptNode.ts
> +	public getPlainTextResultString(): string {
This is never used.. what is the future purpose for this?
Same with getError - never used anywhere.

2022-08-09 06:58 UTC, roman-timo commented on frontend/src/graph/nodes/ScriptNode.ts
> +	public getResult(): ResultPart[] | null {
If we have protected the result with setter, how it can be null?

2022-08-09 06:58 UTC, roman-timo commented on frontend/src/graph/nodes/ScriptNode.ts
> +	}
If we use setResult only for setPlainTextResult - why we need two separate methods? Why this ambiguity?

2022-08-09 06:58 UTC, roman-timo commented on frontend/src/graph/nodes/ScriptNode.ts
> +	public setResult(result: ResultPart[]) {
Why we need to setup a separate result if we dont' have a response?
When we have a response, we use line 55 - to setup a response, which contains a result and error. Why someone could need to setup result as a separate part of response?

2022-08-09 09:56 UTC, AlexFreik commented on frontend/src/graph/AtlasGraph.ts
> +			.map((node) => node as ScriptNode)
I don't know what you mean by "9-times folded function")) 

```ts
something.func1().func2().func3()
````
is just an shortcut for:
```ts
const res1 = something.func1()
const res2 = res1.func2()
const res3 = res2.func3()
```

so it is pretty flat

2022-08-09 10:01 UTC, AlexFreik commented on frontend/src/graph/nodes/AtlasNode.ts
> +	private id = Math.random().toString(36);
just an id that is needed for react-flow

Before it was auto-generated using name, but it 
1. created errors in `react-flow` if user have two nodes with the same name 
2. it can cause issues with react-flow when we update name, but it have the old one

so i decided it is easier to just pre-generate ids.

2022-08-09 10:08 UTC, AlexFreik commented on frontend/src/graph/nodes/ScriptNode.ts
> +	providerNames: string[] = [];
i didn't create it here, i just moved it from ExpressionNode)

But i can explain it anyway is used in here. If ExpressionNode have content `'5 + foo'` then `providerNames` will be equal to `['+', 'foo']` and will be used to generate edges between nodes. 

<img width="623" alt="Screenshot 2022-08-09 at 13 05 45" src="https://user-images.githubusercontent.com/61039123/183622540-6a592fd3-7c5c-4cc1-80fe-b5d1f5f63100.png">

PS: `providerNames` is calculated at `JuliaExecuter`

2022-08-09 10:55 UTC, AlexFreik commented on frontend/src/graph/nodes/ScriptNode.ts
> +	public response: ExecutionResponse | null = null;
It was like this before, so it is not an issue for this PR.

But it is valid point, i made it `null` because there is no response before you executed nodes. But it makes more sense to initialise it with a default value. So i changed it

2022-08-09 10:55 UTC, AlexFreik commented on frontend/src/graph/nodes/ScriptNode.ts
> +		return this.response === null ? null : this.response.error;
i deleted this mehtod

2022-08-09 10:56 UTC, AlexFreik commented on frontend/src/kernels/execution.ts
> +	'text/plain'?: string;
(It was like this before, so it is not an issue for this PR.)

And how do you think we store htmls for grpahs?)

2022-08-09 10:59 UTC, AlexFreik commented on frontend/src/graph/nodes/ScriptNode.ts
> +	public getPlainTextResultString(): string {
I moved this function to `kernel/execution.ts`

PS: it is used) 
<img width="973" alt="Screenshot 2022-08-09 at 13 58 40" src="https://user-images.githubusercontent.com/61039123/183631832-cc924de8-6639-4cfc-8d81-18c27518985a.png">

2022-08-09 10:59 UTC, AlexFreik commented on frontend/src/graph/nodes/ScriptNode.ts
> +	public getResult(): ResultPart[] | null {
changed)

2022-08-09 11:01 UTC, AlexFreik commented on frontend/src/graph/nodes/ScriptNode.ts
> +	}
ambiguity is about different problem, but good point anyway) It was used before, but not rn. I deleted it

2022-08-09 11:02 UTC, AlexFreik commented on frontend/src/graph/nodes/ScriptNode.ts
> +	public setResult(result: ResultPart[]) {
i deleted this method

2022-08-09 12:25 UTC, roman-timo requested changes
just one little part

2022-08-09 12:25 UTC, roman-timo commented on frontend/src/kernels/execution.ts
> +	'text/plain'?: string;
I see you use this for rendering the result in UiNode.tsx. So if I understood correct these two keys are used just as a flag - whether the result is html or string?
If it is so, mabe then it's better to use a flag resultHtml = true/false ? Or (if you like more) - use a type for the result. 
```
interface result {
body: string
type: 'text' | 'html'
}
```

what do you think?

2022-08-09 13:34 UTC, roman-timo approved these changes
nice and smooth :)

2022-08-09 13:35 UTC, merged